### PR TITLE
removed unnecessary `map` call

### PR DESCRIPTION
**Pull request by sarbbottam**
I guess the map call is `unnecessary` here, please close the PR if I have misinterpreted.

### CODE REVIEW

**Comment by xymostech** [comment]
This map is necessary, it recursively calls `fontFamily` on each element of the `fontFamily` array.

**Comment by sarbbottam** [comment]
Thanks @xymostech ! I completely misinterpreted it. Did not encounter a test failure, thus was in doubt.

**Comment by xymostech** [comment]
Yeah, I don't think we have any tests for the `fontFamily` string handler (there's a good place for it here: https://github.com/Khan/aphrodite/blob/master/tests/inject_test.js#L206)

**Comment by sarbbottam** [comment]
I can take it up.

**Pull request closed without merging**
