### PR TITLE
Fix injectAndGetClassName and ignore null values in styleDefinitions

### PR DESCRIPTION
**Pull request by gilbox**
Fixes regression introduced by #248 
@xymostech

### CODE REVIEW

**Comment by gilbox** [comment]
ping @xymostech

**Comment by lencioni** [comment]
Thanks for the fix and the tests!

**Comment by gilbox** [comment]
Ping @xymostech please publish v2.0

**Comment by lencioni** [comment]
I published this as v1.2.4. Thanks for the patience!

**Pull request merged**
