### PR TITLE
add gitter chat badge

### PR DESCRIPTION
**Pull request by kentcdodds**
This isn't setup yet, but I'd like to be :-)

Wanted a place to mention [this](https://twitter.com/kentcdodds/status/718457086519037952).

Also, I want a community to build around this project (hope you're cool with that), and I think this is a good first step :-)

### CODE REVIEW

**Comment by xymostech** [comment]
Looks like `Khan` is spelled incorrectly in the badge. I don't have super strong opinions about where we should set up these sorts of communities. I guess if people use gitter then I should join the bandwagon! (I just set up the room, if you fix the typo I'll merge :)

**Comment by kentcdodds** [comment]
:sweat_smile: thanks! will fix

**Comment by kentcdodds** [comment]
Updated :)

**Comment by xymostech** [comment]
Thanks!

**Comment by xymostech** [comment]
Test comment to trigger gitter?

**Comment by kentcdodds** [comment]
Looks like it worked :-)

**Pull request merged**
