### PR TITLE
Optimize css() some

### PR DESCRIPTION
**Pull request by lencioni**
I am pulling these commits out of #216 because I think they are pretty straightforward and should be easier to merge in this way.

### CODE REVIEW

**Comment by lencioni** [comment]
@xymostech this PR should be pretty straightforward and unblocks some of the improvements I wanted to do on #216. Any chance you are able to take a look soon?

**Comment by lencioni** [comment]
Yeah that's right, but I'm a little nervous about my other PR because of
how it affects plugins and how some of the logic feels a bit spread out. It
might be good to take a step back and see if we can do it more cleanly.

I'm out of town until Tuesday so I probably won't be very responsive until
then.

**Comment by lencioni** [comment]
To close the loop a bit, v1.2.1 just went to production for Airbnb, and it reduced our server rendering times by ~15% (v1.2.0: 285ms, v1.2.1: 245ms). Obviously, this will also help on the client side as well, but the numbers are a little more challenging to consistently measure there.

**Comment by xymostech** [comment]
Thank you so much for pushing this forwards, @lencioni! Glad to hear that it improved performance! :)

**Pull request merged**
