### PR TITLE
:memo: we support animations

### PR DESCRIPTION
**Pull request by basarat**
Did a search on the page and thought perhaps it wasn't supported. Googled, found answer so sent this PR :rose:

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome :clap:

**Comment by jlfwong** [comment]
Hi @basarat!

That is indeed a hole in our docs!

It would be great if you could add a section right below "Font Faces" about how this feature is used.

You can find an example usage here: https://github.com/Khan/aphrodite/blob/master/tests/inject_test.js#L352

Thanks!

**Comment by kentcdodds** [comment]
Also relevant :) https://www.youtube.com/watch?v=BIpKF_CMhu8&list=PLo4Zh55ZzNSBP78pCD0dZJi9zf8CA72_M&index=4

**Comment by xymostech** [comment]
@basarat Awesome! We use the `animationName` property actually. :)

**Comment by basarat** [comment]
> We use the animationName property actually

I think is `animation: keyframes, animationName: nameStringUsedToRegisterTheKeyframes`

**Comment by xymostech** [comment]
> I think is animation: keyframes, animationName: nameStringUsedToRegisterTheKeyframes

You can read the source yourself, we only use the `animationName` property: https://github.com/Khan/aphrodite/blob/master/src/inject.js#L60

**Comment by basarat** [comment]
> we only use the animationName property:

Yup. My bad. 

Closing to let some other hero take it over :rose:

**Pull request closed without merging**
