### PR TITLE
Add note about unicode characters in `content`

### PR DESCRIPTION
**Pull request by jaredly**
This had me stuck for a while... figured I'd leave a note for the next person

### CODE REVIEW

**Comment by jlfwong** [comment]
Making the example use font-awesome is pretty weird...

Why not 'Aphrodite 💖' as the example instead? :D

**Comment by spicyj** [comment]
Woah weird, can you not put unicode characters in between quotes in CSS?

**Comment by jaredly** [comment]
With a heart you would just put `content: '"💖"'`, because it's renderable by a normal font. Only with an icon-font like font-awesome would you use the `\f1db` format

**Comment by spicyj** [comment]
Oh okay. But "\uF1DB" in the JS string should work right?

**Pull request closed without merging**
