### PR TITLE
Support multiple animation names

### PR DESCRIPTION
**Pull request by joshwcomeau**
* Updated the `animationName` handler to accept arrays of animation
  names
* Added an example showcasing two asynchronous animations
* Updated documentation to include info about single and multiple
  animations.
* closes https://github.com/Khan/aphrodite/issues/78

### CODE REVIEW

**Comment by joshwcomeau** [comment]
[clabot:check]

**Comment by xymostech** [comment]
This all looks great to me! I'll let @jlfwong give it a look before we merge.

**Comment by jlfwong** [comment]
LGTM! Thanks @joshwcomeau! Implementation simple and clean, with docs + tests ❤️ 

@xymostech Can you merge and push a new minor release to npm?

**Comment by xymostech** [comment]
@jlfwong done!

**Pull request merged**
