### PR TITLE
using object shorthand

### PR DESCRIPTION
**Pull request by sarbbottam**
Similar to [aphrodite/src/index.js#L59-L63](https://github.com/Khan/aphrodite/blob/master/src/index.js#L59-L63)
```js
export default {
    StyleSheet,
    StyleSheetServer,
    css,
};
```

### CODE REVIEW

**Comment by xymostech** [comment]
I think this obscures what the structure of the return value of this function is.

**Comment by sarbbottam** [comment]
Does this sound better?

```diff
-const html = renderFunc();
-const cssContent = flushToString();

return {
-    html: html,
+    html: renderFunc(),
    css: {
-        content: cssContent,
+        content: flushToString(),
        renderedClassNames: getRenderedClassNames(),
    },
};
```

May be, I don't follow the rational of caching the content of `html` and `css.content` in a local variable, and not for `renderedClassNames`. Any specific reason?

**Comment by xymostech** [comment]
We need to ensure that `renderFunc()` is called before `flushToString()` or `getRenderedClassNames()`, which is why it's separate (I don't know if it's specified which order things will execute). I can't remember if it's necessary that `flushToString()` comes before `getRenderedClassNames()`, but it might be?

**Comment by sarbbottam** [comment]
Ahh, I see, thanks for the clarification, I guess it would be better, to add these comments in-line, to avoid unnecessary PRs and ... 

> I can't remember if it's necessary ...

**Pull request closed without merging**
