### PR TITLE
Update inline-style-prefixer, add transition: border-color test

### PR DESCRIPTION
**Pull request by gscottolson**
Fixes https://github.com/Khan/aphrodite/issues/96

### CODE REVIEW

**Comment by gscottolson** [comment]
Do I need to include the compiled files in the `/dist` folder, too?

**Comment by kentcdodds** [comment]
< insert my regular (annoying) reminder about how it'd be handy to [not commit generated files](http://kcd.im/generated) to source control >

@gscottolson, no, I believe that the project maintainers generate that themselves for releases only.

**Comment by jlfwong** [comment]
@gscottolson Woohoo! Thanks for the PR. I trust the test fails when using the old version of the autoprefixer?

Yeah, it's fine -- no need to commit the generated files.

Can you sign the Khan Academy CLA if you haven't already, please? https://docs.google.com/forms/d/1QIZDwzdLrqyqGkqzVcMHEFSaApt_IZkGmgSnRkArvzI/viewform

@kentcdodds It's for interop reasons with Khan Academy's codebase, and would be sort of a PITA to fix. I also don't work there any more, so it's not really something in my control any more either :)

**Comment by gscottolson** [comment]
@jlfwong Signed the CLA. And yes, the old version fails with this test, as described in https://github.com/Khan/aphrodite/issues/96.

**Comment by jlfwong** [comment]
@gscottolson Thanks!

**Pull request merged**
