### PR TITLE
add conditional css API example

### PR DESCRIPTION
**Pull request by kentcdodds**
ref: https://github.com/Khan/aphrodite/pull/114#issuecomment-235669930

### CODE REVIEW

**Comment by xymostech** [comment]
Thank you for adding this! Some comments:

- I would add a note like "any falsey arguments will be ignored. So, styles can be applied conditionally..." to make it clear why this works.
- Could you put each condition on a separate line so the example is easier to read and so it isn't too wide?
- You could just make this into a section, like "Conditionally applying styles" or something

**Comment by kentcdodds** [comment]
Great feedback. Updated 👍

**Comment by kentcdodds** [comment]
Here's what it looks like:

screen shot 2016-07-27 at 1 29 48 pm

**Comment by xymostech** [comment]
LGTM! @jlfwong any thoughts?

**Comment by jlfwong** [comment]
Thanks!

**Pull request merged**
